require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION = "2"

homesteadYamlPath = File.expand_path("~/code/envs/ci/ENVIRONMENT/Homestead.yaml")
afterScriptPath = File.expand_path("~/code/envs/ci/ENVIRONMENT/after.sh")
aliasesPath = File.expand_path("~/code/envs/ci/ENVIRONMENT/aliases")

require_relative 'scripts/homestead.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

	if File.exists? aliasesPath then
		config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
	end

	Homestead.configure(config, YAML::load(File.read(homesteadYamlPath)))

	if File.exists? afterScriptPath then
		config.vm.provision "shell", path: afterScriptPath
	end
end
